### ISSUE TITLE
很棒的工作！但反映一个问题，论文中的PVT的引用全错了... 

### ISSUE THREAD

**Issue by amusi** [wofmanaf/ResT#1]
论文中的PVT[5]引用的全是ViT[5]，实际应该是：Pyramid Vision Transformer: A Versatile Backbone for Dense Prediction without Convolutions，参考文献中没有，需要新加这个文献

**Comment by wofmanaf** [comment]
嗯嗯，谢谢您的提醒，我们将在下一个arxiv版本中更正过来，多谢多谢

**Comment by wofmanaf** [comment]
我们在arxiv上提交了[v2版本](https://arxiv.org/pdf/2105.13677v2.pdf) ，已经将PVT的引用修改过来了，readme中的链接地址也改成了v2版本的。再次谢谢您的提醒
