### ISSUE TITLE
How to calculate FLOPS on ResT

### ISSUE THREAD

**Issue by chakkritte** [wofmanaf/ResT#13]
Hi @wofmanaf 

Thank you for your source code.
Can you share source code to calculate the number of FLOPS on ResT models ?

Best,

Chakkrit

**Comment by wofmanaf** [comment]
- pip install [mmcv](https://github.com/open-mmlab/mmcv)

- copy the following code to calculate the Param and FLOPS.

```bash
    from mmcv.cnn.utils import get_model_complexity_info
    model = rest_lite()
    flops_count, params_count = get_model_complexity_info(model, input_shape=(3, 224, 224))
    print("flops: ", flops_count)
    print("params: ", params_count)
```

**Comment by chakkritte** [comment]
Thank you for your reply.
