### ISSUE TITLE
用ResTv1做主干，做目标检测出现张量错误

### ISSUE THREAD

**Issue by Zhuyuan-yuan** [wofmanaf/ResT#22]
做目标检测 类别为1 运行时出现下面的错误，这是什么原因？
<img width="682" alt="image" src="https://user-images.githubusercontent.com/72205719/167813520-7d2b7b59-54c9-4dd8-a094-86b3b58194eb.png">

**Comment by wofmanaf** [comment]
这个应该是x的空间维度不能被H和W整除造成的，一般在做目标检测的时候都需要，都需要做一下size_vidisibility，detectron2中默认为32。这样骨干网络经过4个stage之后，依然能够保证整除，具体事例：
https://github.com/wofmanaf/ResT/blob/346d4a8f7fae74d8e9841937045547ce5b8b4b46/object_detection/restv2/restv2.py#L305-L307

**Comment by Zhuyuan-yuan** [comment]
非常感谢您的解答，问题已解决！
