### ISSUE TITLE
大佬，能不能把V2的预训练模型发一份google drive

### ISSUE THREAD

**Issue by 1deepgroupe1** [wofmanaf/ResT#24]
或者那个V2百度网盘的提取密码能告知下吗？

**Comment by C-C-Y** [comment]
> 你好，你获得预训练模型了么

**Comment by 1deepgroupe1** [comment]
他上面是已经给了，你仔细看下。
&nbsp;


QAQ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Double ***@***.***&gt;; 
发送时间: 2023年2月20日(星期一) 中午12:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [wofmanaf/ResT] 大佬，能不能把V2的预训练模型发一份google drive (Issue #24)





  
你好，你获得预训练模型了么

**Comment by C-C-Y** [comment]
> 他上面是已经给了，你仔细看下。 &nbsp; QAQ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Double ***@***.***&gt;; 发送时间: 2023年2月20日(星期一) 中午12:57 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [wofmanaf/ResT] 大佬，能不能把V2的预训练模型发一份google drive (Issue #24) 你好，你获得预训练模型了么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

你好，百度盘我试了下需要密码，主页有一份发在谷歌云盘上的是v1的，v2的我没找到，麻烦能指示下么

**Comment by 1deepgroupe1** [comment]
密码就在那个链接表格的下面写着
&nbsp;


QAQ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Double ***@***.***&gt;; 
发送时间: 2023年2月20日(星期一) 中午1:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [wofmanaf/ResT] 大佬，能不能把V2的预训练模型发一份google drive (Issue #24)





  
他上面是已经给了，你仔细看下。 &nbsp; QAQ @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Double @.&gt;; 发送时间: 2023年2月20日(星期一) 中午12:57 收件人: @.&gt;; 抄送: @.&gt;; "State @.&gt;; 主题: Re: [wofmanaf/ResT] 大佬，能不能把V2的预训练模型发一份google drive (Issue #24) 你好，你获得预训练模型了么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
你好，百度盘我试了下需要密码，主页有一份发在谷歌云盘上的是v1的，v2的我没找到，麻烦能指示下么

**Comment by 1deepgroupe1** [comment]
我付费的梯子到期了，github上不去。不好意思，你仔细看下。
如果你开页面翻译了，就把翻译给关了，我当初就是开了翻译密码给覆盖了

QAQ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wofmanaf/ResT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 中午1:39
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [wofmanaf/ResT] 大佬，能不能把V2的预训练模型发一份google drive (Issue #24)





  
他上面是已经给了，你仔细看下。 &nbsp; QAQ @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Double @.&gt;; 发送时间: 2023年2月20日(星期一) 中午12:57 收件人: @.&gt;; 抄送: @.&gt;; "State @.&gt;; 主题: Re: [wofmanaf/ResT] 大佬，能不能把V2的预训练模型发一份google drive (Issue #24) 你好，你获得预训练模型了么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
你好，百度盘我试了下需要密码，主页有一份发在谷歌云盘上的是v1的，v2的我没找到，麻烦能指示下么

**Comment by C-C-Y** [comment]
> 我付费的梯子到期了，github上不去。不好意思，你仔细看下。 如果你开页面翻译了，就把翻译给关了，我当初就是开了翻译密码给覆盖了 QAQ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wofmanaf/ResT" ***@***.***&gt;; 发送时间:&nbsp;2023年2月20日(星期一) 中午1:39 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [wofmanaf/ResT] 大佬，能不能把V2的预训练模型发一份google drive (Issue #24) 他上面是已经给了，你仔细看下。 &nbsp; QAQ @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Double @.&gt;; 发送时间: 2023年2月20日(星期一) 中午12:57 收件人: @.&gt;; 抄送: @.&gt;; "State @.&gt;; 主题: Re: [wofmanaf/ResT] 大佬，能不能把V2的预训练模型发一份google drive (Issue #24) 你好，你获得预训练模型了么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt; 你好，百度盘我试了下需要密码，主页有一份发在谷歌云盘上的是v1的，v2的我没找到，麻烦能指示下么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

非常谢谢你❤，是我粗心没注意到
