### ISSUE TITLE
arxiv上 v2 版本中图四的排版问题

### ISSUE THREAD

**Issue by zyrant** [wofmanaf/ResT#3]
您好

        我从https://arxiv.org/pdf/2105.13677v2.pdf下载了最新的版本，但是其中第5页的figure4存在排版问题。

zy

**Comment by wofmanaf** [comment]
嗯嗯，我重新核对了一下，图4确实存在排版问题，该问题将会在v3版本中更正。多谢提醒

**Comment by wofmanaf** [comment]
图4的排版问题在[v3](https://arxiv.org/pdf/2105.13677v3.pdf)已经更正， v3版本添加了对MSA和EMSA的比较，并对如何更好地将ResT应用于下游任务中进行了简单地探讨
