### ISSUE TITLE
rest.py

### ISSUE THREAD

**Issue by mzprose** [wofmanaf/ResT#6]
Hello, if I want to try your backborn on other visual tasks, can I call rest.py directly?

**Comment by wofmanaf** [comment]
No, the usage and pre-trained weights of ResT on downstream tasks, such as object detection, instance segmentation will be available on Monday.

**Comment by wofmanaf** [comment]
The code and pre-trained weights of ResT on downstream tasks have been released.

**Comment by mzprose** [comment]
OK，thanks for your reply！！！
